language: rust
sudo: false

cache:
  - cargo

rust:
  - stable
# --------------------------------- Travis ----------------------------------
notifications:
  email: false

branches:
  # Ensures when "Build pushed branches is enabled" in Travis setting, then only the below branches will execute the build
  # Note: When "Build pushed pull requests" is enabled then all open PR are built with every commit pushed.
  only:
    - master
    - develop

git:
  depth: false
  quiet: true

# --------------------------------- Install ---------------------------------
install:
  - cargo install mdbook

# --------------------------------- Script ----------------------------------
before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - mdbook build && mdbook test

# ------------------------ Deploy to Github Pages ---------------------------
deploy:
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
local-dir: book
keep-history: false
on:
  branch: develop
